---
controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints: [shoulder, arm, arm2, gripper_joint]
initial: []  # Define initial robot poses per group
#  - group: manipulator
#    pose: home
