---
ros_control_namespace: /arm/rrbot_hardware_interface
manipulator_controller:
  type: effort_controllers/JointTrajectoryController
  joints: [shoulder, arm, arm2, gripper_joint]
  gains:
    shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
