---
name: python style check
on: [push, pull_request]
jobs:
  check-python-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Black Code Formatter
        uses: lgeiger/black-action@master
        with:
          args: . --check
