---
my_robot:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  
mobile_base_controller:
  ticks: 330  # TODO: check 11pps*30reduction
  type: mecanum_drive_controller/MecanumDriveController
  front_left_wheel_joint: wheel_left_front_joint
  back_left_wheel_joint: wheel_left_rear_joint
  front_right_wheel_joint: wheel_right_front_joint
  back_right_wheel_joint: wheel_right_rear_joint
  publish_rate: 50
  pose_covariance_diagonal:
    - 0.001
    - 0.001
    - 1000000.0
    - 1000000.0
    - 1000000.0
    - 0.03
  twist_covariance_diagonal:
    - 0.001
    - 0.001
    - 0.001
    - 1000000.0
    - 1000000.0
    - 0.03
  cmd_vel_timeout: 0.25

  # Override URDF look-up for wheel separation since the parent link is not the base_link.
  wheel_separation_x: 0.638
  wheel_separation_y: 0.551
  wheel_radius: 0.08  # 8cm
  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: true

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0  # default: 1.0
  wheel_radius_multiplier: 1.0  # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits: false
      max_velocity: 1.1  # m/s
      has_acceleration_limits: false
      max_acceleration: 2.5  # m/s^2
    y:
      has_velocity_limits: false
      max_velocity: 1.1  # m/s
      has_acceleration_limits: false
      max_acceleration: 2.5  # m/s^2
  angular:
    z:
      has_velocity_limits: false
      max_velocity: 2.0  # rad/s
      has_acceleration_limits: false
      max_acceleration: 1.0  # rad/s^2
# ekf_localization:
#   frequency: 50
#   two_d_mode: true
#   odom0: /ridgeback_velocity_controller/odom
#   odom0_config: [false, false, false,
#                  false, false, false,
#                  true, true, false,
#                  false, false, true,
#                  false, false, false]
#   odom0_differential: false
#   imu0: /imu/data
#   imu0_config: [false, false, false,
#                 false, false, false,
#                 false, false, false,
#                 false, false, true,
#                 true, true, false]
#   imu0_differential: false
#   odom_frame: odom
#   base_link_frame: base_link
#   world_frame: odom
#   predict_to_current_time: true
