device:
  mirte:
    type: pcb
    version: 0.6
    max_frequency: 50
modules:
  motorservocontroller:
    device: mirte
    type: PCA9685
    id: 0x41 # bridged A0
    connector: I2C1
    frequency: 1500
    motors:
      left_front:
        pin_A: 1
        pin_B: 0
      left_rear:
        pin_A: 3
        pin_B: 2
      right_rear:
        pin_A: 4
        pin_B: 5
      right_front:
        pin_A: 6
        pin_B: 7
  servo_controller:
    device: mirte
    type: Hiwonder_Servo
    uart: 0
    rx_pin: 0
    tx_pin: 1
    servos:
      servoH1:
        id: 3
        min_angle_out: 9000
        max_angle_out: 14000
        home_out: 1000
        invert: false
      servoH2:
        id: 4 
        min_angle_out: 800
        max_angle_out: 4000
        home_out: 1000
        invert: false
  power_watcher:
    device: mirte
    type: INA226
    connector: I2C1
    id: 0x40 # default id
    min_voltage: 11
    max_current: 1
    max_voltage: 15
    switch_pin: GP28
    switch_off_value: True
    switch_pull: 1 # -1 for pulldown, 1 for pullup, 0 for none
    switch_time: 5
    # turn_off_pin: 27
    # turn_off_value: True
    # turn_off_time: 10
    percentage_led_chip: gpiochip4
    percentage_led_line: 12 # B4, left-most led on usb switcher pcb
  movement:
    type: MPU9250
    connector: I2C1
    device: mirte
    id: 0x68
# encoder:
#   left_front:
#     name: left_front
#     device: mirte
#     pins:
#       A: 21
#       B: 20
#   left_rear:
#     name: left_rear
#     device: mirte
#     pins:
#       A: 17
#       B: 16
#   right_front:
#     name: right_front
#     device: mirte
#     pins:
#       A: 18
#       B: 19
#   right_rear:
#     name: right_rear
#     device: mirte
#     pins:
#       A: 15
#       B: 14
neopixel:
  name: leds
  pins:
    pin: 27
  default_color: 0xF
  max_intensity: 50
  pixels: 100
intensity:
  left:
    name: left
    device: mirte
    pins:
      analog: GP26
      digital: GP10
oled:
  middle:
    device: mirte
    connector: I2C1
    show_hostname: True
    show_ip: True
    show_wifi: True
    show_soc: True
# neopixel:
#   name: leds
#   pins:
#     pin: 27
#   default_color: 0x123456
#   max_intensity: 50
#   pixels: 18


    # servos:
    #   servo1:
    #     pin: 1
  # servo_controller:
  #   device: mirte
  #   type: Hiwonder_Servo
  #   uart: 0
  #   rx_pin: 0
  #   tx_pin: 1
  #   servos:
  #     servoH1:
  #       id: 3
  #       min_angle: 9000
  #       max_angle: 14000
  #     servoH2:
  #       id: 4
  #       min_angle: 800
  #       max_angle: 4000
  # power_watcher:
  #   device: mirte
  #   type: INA226
  #   connector: I2C1
  #   id: 0x41
  #   min_voltage: 11.18
  #   max_current: 1
  #   max_voltage: 13.0
