device:
  mirte:
    type: breadboard
    board: raw             # current setup is an example for the arduino nano
#    max_frequency: 50
distance:
  left:
    name: left
    device: mirte
    pins:
      trigger: 17
      echo: 18
  right:
    name: right
    device: mirte
    pins:
      trigger: 19
      echo: 20
encoder:
  left:
    name: left
    device: mirte
    pins:
      pin: 2             # pin needs interrupt support
    ticks_per_wheel: 20
  right:
    name: right
    device: mirte
    pins:
      pin: 3             # pin needs interrupt support
    ticks_per_wheel: 20
intensity:
  left:
    name: left 
    device: mirte
    max_frequency: 10
    differential: 0
    pins:
      digital: 7
      analog: 0          # pin needs analog input
  right:
    name: right
    device: mirte
    pins:
      digital: 8
      analog: 1          # pin needs analog input
#oled:
#  left_oled:
#    device: mirte
#    pins:
#      scl: A5
#      sda: A4
servo:
  device: mirte
  pins:
    pin: 11               # pin needs PWM
keypad:
  yellow:
    name: keypad
    device: mirte
    pins:
      pin: 2              # pin needs analog input
motor:
  left:
    name: left
    device: mirte
    type: dp
    pins:
      d1: 5
      p1: 6
  right:
    name: right
    device: mirte
    type: dp
    pins:
      d1: 9
      p1: 10
