device:
  mirte:
    type: breadboard
    board: nanoatmega328
#    max_frequency: 50
distance:
  left:
    name: left
    device: mirte
    pins:
      trigger: A3
      echo: A4
  right:
    name: right
    device: mirte
    pins:
      trigger: A5
      echo: A6
encoder:
  left:
    name: left
    device: mirte
    pins:
      pin: D2            # pin needs interrupt support
    ticks_per_wheel: 20
  right:
    name: right
    device: mirte
    pins:
      pin: D3            # pin needs interrupt support
    ticks_per_wheel: 20
intensity:
  left:
    name: left 
    device: mirte
    max_frequency: 10
    differential: 0
    pins:
      digital: D7
      analog: A0         # pin needs analog input
  right:
    name: right
    device: mirte
    pins:
      digital: D8
      analog: A1         # pin needs analog input
oled:
  left_oled:
    device: mirte
    pins:
      scl: A5
      sda: A4
servo:
  left:
    name: left
    device: mirte
    pins:
      pin: D9               # pin needs PWM
  right:
    name: right
    device: mirte
    pins:
      pin: D10               # pin needs PWM
keypad:
  yellow:
    name: keypad
    device: mirte
    pins:
      pin: A2              # pin needs analog input
motor:
  left:
    name: left
    device: mirte
    type: ddp
    pins:
      d1: D7
      d2: D8
      p1: D5
  right:
    name: right
    device: mirte
    type: ddp
    pins:
      d1: D4
      d2: D12
      p1: D6
